name: run-tests

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.1, 7.2, 7.3, 7.4, 8.0, 8.1]
        testsuite: ["unit"]
    name: PHPUnit - ${{ matrix.testsuite }} (PHP ${{ matrix.php }})
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: spoon_tests
          MYSQL_ROOT_PASSWORD: "spoon"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, bcmath, intl, gd, exif, iconv, imagick
          coverage: xdebug # Switch to PCOV for a speed gain when we can use PHP 7.2 & PHPUnit 8.0.

      - name: Install dependencies
        env:
          FORK_ENV: test
          SYMFONY_DEPRECATIONS_HELPER: "quiet"
        run: composer install -o

      - name: Execute tests
        env:
          SYMFONY_DEPRECATIONS_HELPER: "quiet"
        run: vendor/bin/simple-phpunit --testsuite=${{ matrix.testsuite}} --coverage-clover=${{ matrix.testsuite}}.clover

      - name: Upload Coverage report
        uses: codecov/codecov-action@v1
        with:
          file: ${{ matrix.testsuite}}.clover
          flags: ${{ matrix.testsuite}}
